### PR TITLE
Wordpress update script/jquery.videobackground.js

### PR DESCRIPTION
**Pull request by ccevans**

### CODE REVIEW

**Comment by ccevans** [comment]
Wordpress update

**Comment by georgepaterson** [comment]
Thanks for the patch but it seems unnecessary? The plugin itself is a self executing function that map jQuery to the dollar sign, eliminating conflict.

(function( $ ) {
  ...
})( jQuery );

To make the plugin work in Wordpress you just need to call it using jQuery rather than the dollar sign.

jQuery('.video-background').videobackground({ ... });

This works as my own site is Wordpress http://www.georgepaterson.com/sandbox/jquery-html5-video-background-demo/

**Comment by ccevans** [comment]
Thanks,

So I need to change all the $ in the script to jQuery?

On Tue, Dec 20, 2011 at 5:37 AM, George Paterson <
reply@reply.github.com

**Comment by georgepaterson** [comment]
You just need the invocation of the plugin to use jQuery: jQuery('.video-background').videobackground({ ... });

The plugin code is hidden to Wordpress so no conflict and $ is fine. I found this out the painful way as well.

**Pull request closed without merging**
